pyodbc.cpython-311-x86_64-linux-gnu.so,sha256=8Q-FNRdKtfVBkrTRZqlYPirPj9nOugpnLNKErKOoIXI,952529
pyodbc-5.0.0b1.data/data/pyodbc.pyi,sha256=T31FTRfejtgEzZcRCrOYg_O-0JOol6SRAF0guq2ri20,32184
pyodbc-5.0.0b1.dist-info/RECORD,,
pyodbc-5.0.0b1.dist-info/WHEEL,sha256=48wUIcZcdQ2pWN7qt0HP02Cvv6HIQZGsSgx3PsepNj8,152
pyodbc-5.0.0b1.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0b1.dist-info/METADATA,sha256=ShoNudbLun7Gd3s8wLIpSS83j-AjhZs8Pk13riYiPeU,2431
pyodbc-5.0.0b1.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
