pyodbc.cpython-37m-aarch64-linux-gnu.so,sha256=TDFILF8MM74Y_D1WgodfQzF3MIkGOH8Cx-_HNYQcBg8,989361
pyodbc-5.0.0b2.data/data/pyodbc.pyi,sha256=rx05N8EYqujKI3FWtMikUjqMPTv4VQg0ChXny9DaisE,32326
pyodbc-5.0.0b2.dist-info/RECORD,,
pyodbc-5.0.0b2.dist-info/WHEEL,sha256=neWuJ1LnrHaY8l7MEw7BZcfHReCbIl12Pb5uwIiJ5iM,152
pyodbc-5.0.0b2.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0b2.dist-info/METADATA,sha256=OYj_kB8kxLgAvzUB3IK51kZWub0HI3h3dSxdnHa2Oc0,2719
pyodbc-5.0.0b2.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
