pyodbc.cpython-38-x86_64-linux-gnu.so,sha256=gkOYu4JqnCezz7MG8xJ34cdX1gO7kNWohvR6Y_1uGX0,923889
pyodbc-5.0.0b2.data/data/pyodbc.pyi,sha256=rx05N8EYqujKI3FWtMikUjqMPTv4VQg0ChXny9DaisE,32326
pyodbc-5.0.0b2.dist-info/RECORD,,
pyodbc-5.0.0b2.dist-info/WHEEL,sha256=CzyHWKXay4N1oFds0wxFofK9MEs-L6SZ6gHGZF6-4Co,148
pyodbc-5.0.0b2.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0b2.dist-info/METADATA,sha256=OYj_kB8kxLgAvzUB3IK51kZWub0HI3h3dSxdnHa2Oc0,2719
pyodbc-5.0.0b2.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
