pyodbc.cpython-39-x86_64-linux-gnu.so,sha256=0MCJeNNQRRhJoqju4umgeId7PRHR6lCOAq5J4tQ6UL8,845865
pyodbc-5.0.0a2.dist-info/RECORD,,
pyodbc-5.0.0a2.dist-info/WHEEL,sha256=_BMdtp3IQ4NF7VFMKD4lD9Cik0H3WhEP1vtG22VwXhU,148
pyodbc-5.0.0a2.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0a2.dist-info/METADATA,sha256=rmKkah_waYVn7-pIvd_Nu8DsAeuAQxTTAVQpJ9DZKlw,2431
pyodbc-5.0.0a2.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-5.0.0a2.data/data/pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
