pyodbc.cpython-39-aarch64-linux-gnu.so,sha256=PXiBZTgnLh7Tgjz9eZkbZxNODLWtfF7CAcNK6DAL8n8,989393
pyodbc-5.0.0b1.data/data/pyodbc.pyi,sha256=T31FTRfejtgEzZcRCrOYg_O-0JOol6SRAF0guq2ri20,32184
pyodbc-5.0.0b1.dist-info/RECORD,,
pyodbc-5.0.0b1.dist-info/WHEEL,sha256=D_hVsWGC2Sa0k2QN17ttoKd_qC8kp7xu6xCx6TJmGcs,150
pyodbc-5.0.0b1.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-5.0.0b1.dist-info/METADATA,sha256=ShoNudbLun7Gd3s8wLIpSS83j-AjhZs8Pk13riYiPeU,2431
pyodbc-5.0.0b1.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
